### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by saivivekseeram1** [openvinotoolkit/openvino_notebooks#1990] opened 2024-05-02 09:18 UTC
Notebook-model name: **Image generation with DeepFloyd IF and OpenVINO.**
Running Notebook At Text Encode Inference, Error was raised: "**Permission Error- [WinError 32] The Process cannot access the file becuase it is being used by another process**"

"Just a heads up: I'm only running this notebook here, not executing it anywhere else."

For your reference i'm attaching the screenshots below .
![Screenshot 2024-04-30 175954](https://github.com/openvinotoolkit/openvino_notebooks/assets/92068535/6d32f0ea-a6d3-48a4-b3d2-dcc55204134c)

**Comment by andrei-kochin** [comment] 2024-05-06 10:19
@saivivekseeram1 it looks like you've executed the cell twice accessing the same file. Is this issue reproducible in case you run all cells?

**Comment by Aznie-Intel** [comment] 2024-05-13 23:32
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Closed by Aznie-Intel** 2024-05-13 23:32 UTC
Labels: support_request

**Comment by saivivekseeram1** [comment] 2024-05-23 09:18
> @saivivekseeram1 it looks like you've executed the cell twice accessing the same file. Is this issue reproducible in case you run all cells?
No, I am only facing this issue while executing the cell. And I have executed it entire cells from the beginning, still the issue was same
