### ISSUE TITLE
231-instruct-pix2pix-image-editing gives runtime error at the diffusion process

### ISSUE THREAD

**Issue by gitist** [openvinotoolkit/openvino_notebooks#1472] opened 2023-11-16 23:27 UTC
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[11], line 13
     11 print(f'Number of steps: {num_steps.value}')
     12 np.random.seed(seed.value)
---> 13 processed_image = ov_pipe(text_prompt.value, image, num_steps.value)

Cell In[6], line 174, in OVInstructPix2PixPipeline.__call__(self, prompt, image, num_inference_steps, guidance_scale, image_guidance_scale, eta, latents, output_type)
    171 scheduler_is_in_sigma_space = hasattr(self.scheduler, "sigmas")
    173 # 2. Encode input prompt
--> 174 text_embeddings = self._encode_prompt(prompt)
    176 # 3. Preprocess image
    177 orig_width, orig_height = image.size

Cell In[6], line 291, in OVInstructPix2PixPipeline._encode_prompt(self, prompt, num_images_per_prompt, do_classifier_free_guidance)
    282 text_inputs = self.tokenizer(
    283     prompt,
    284     padding="max_length",
   (...)
    287     return_tensors="np",
    288 )
    289 text_input_ids = text_inputs.input_ids
--> 291 text_embeddings = self.text_encoder(
    292     text_input_ids)[self.text_encoder_out]
    294 # duplicate text embeddings for each generation per prompt, using mps friendly method
    295 if num_images_per_prompt != 1:

File ~/github/OV_chatbot/notebooks/231-instruct-pix2pix-image-editing/231-venv/lib/python3.10/site-packages/openvino/runtime/ie_api.py:384, in CompiledModel.__call__(self, inputs, share_inputs, share_outputs, shared_memory)
    381 if self._infer_request is None:
    382     self._infer_request = self.create_infer_request()
--> 384 return self._infer_request.infer(
    385     inputs,
    386     share_inputs=_deprecated_memory_arg(shared_memory, share_inputs),
    387     share_outputs=share_outputs,
    388 )

File ~/github/OV_chatbot/notebooks/231-instruct-pix2pix-image-editing/231-venv/lib/python3.10/site-packages/openvino/runtime/ie_api.py:143, in InferRequest.infer(self, inputs, share_inputs, share_outputs, shared_memory)
     68 def infer(
     69     self,
     70     inputs: Any = None,
   (...)
     74     shared_memory: Any = None,
     75 ) -> OVDict:
     76     """Infers specified input(s) in synchronous mode.
     77 
     78     Blocks all methods of InferRequest while request is running.
   (...)
    141     :rtype: OVDict
    142     """
--> 143     return OVDict(super().infer(_data_dispatch(
    144         self,
    145         inputs,
    146         is_shared=_deprecated_memory_arg(shared_memory, share_inputs),
    147     ), share_outputs=share_outputs))

RuntimeError: Exception from src/inference/src/infer_request.cpp:231:
Check 'found_port.found()' failed at src/inference/src/dev/isync_infer_request.cpp:213:
Cannot find tensor for port input_ids[0]:i64[1,77]

 **Expected behavior**
Run all cells without erros

 **Installation instructions (Please mark the checkbox)**
[ check ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.

Here is the output of check_install.py:

(231-venv) 
$~/github/OV_chatbot (main) ⚡ 
❯ python --version                                                                                                                                                                                          ⏎
Python 3.10.13
(231-venv) 
$ ~/github/OV_chatbot (main) ⚡ 
❯ python check_install.py 
System information:
Python executable: /home/ssabet/github/OV_chatbot/notebooks/231-instruct-pix2pix-image-editing/231-venv/bin/python
Pip version: 23.3.1
OpenVINO source: /home/ssabet/github/OV_chatbot/notebooks/231-instruct-pix2pix-image-editing/231-venv/lib/python3.10/site-packages/openvino
OpenVINO IE version: 2023.2.0-13089-cfd42bd2cb0-HEAD
OpenVINO environment activated: NOT OK
Jupyter kernel installed for openvino_env: NOT OK
Python version: 3.10 NOT OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK

It appears that you are not running Python in an `openvino_env` 
environment. It is possible use the notebooks in a different 
environment, but if you run into trouble, please follow the instructions 
in the README to install and activate the `openvino_env` environment.

The Python version in openvino_env does not match the openvino_env Jupyter kernel.
This may not be an issue. If you experience issues, please follow the instructions
in the README to reinstall the kernel.

The README.md file is located in the openvino_notebooks directory 
and at https://github.com/openvinotoolkit/openvino_notebooks
(231-venv)

**Additional context**
Model name:                         Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
/dev/nvme0n1p2  916G  435G  435G  51% /
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
(231-venv)

**Comment by eaidova** [comment] 2023-11-17 05:23
@gitist  hello, I'm not able reproduce provided error. maybe there is something additional specific details?
which pytorch, transformers and diffusers version do you use?

**Comment by andrei-kochin** [comment] 2023-12-06 06:44
@gitist any updates?

**Comment by avitial** [comment] 2023-12-18 22:00
Closing this as it can't be reproduced due to insufficient info. Feel free to reopen and share any relevant details, or to ask additional questions related to this topic if issue persists.

**Closed by avitial** 2023-12-18 22:00 UTC
Labels: support_request
