### ISSUE TITLE
240-dolly-2-instruction-following fails to use AUTO as device

### ISSUE THREAD

**Issue by dnoliver** [openvinotoolkit/openvino_notebooks#1302] opened 2023-09-08 18:56 UTC
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

240-dolly-2-instruction-following, using AUTO as the target device cause an error in Cell 3.

```

```

Switching it to CPU makes it work

 **Expected behavior**

AUTO should work

**Screenshots**

Result of running the notebook set with AUTO:

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/7730267/bf789461-d5ad-4b6d-883e-79e1ee56b294)

 **Installation instructions (Please mark the checkbox)**
[x] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
```
root@ubuntu:/opt/intel/openvino_notebooks# python3 check_install.py  
Traceback (most recent call last):                                                                                                                                        
  File "/opt/intel/openvino_notebooks/check_install.py", line 7, in <module> 
    import pip                                                                       
ModuleNotFoundError: No module named 'pip'                                           
root@ubuntu:/opt/intel/openvino_notebooks# source /opt/intel/openvino_venv/bin/activate      
(openvino_venv) root@ubuntu:/opt/intel/openvino_notebooks# python check_install.py  
System information:                     
Python executable: /opt/intel/openvino_venv/bin/python 
Pip version: 23.2.1                     
OpenVINO source: /opt/intel/openvino_venv/lib/python3.10/site-packages/openvino 
OpenVINO IE version: 2023.1.0-12050-e33de350633 
OpenVINO environment activated: NOT OK
Jupyter kernel installed for openvino_env: NOT OK 
Python version: 3.10 NOT OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: NOT OK

It appears that you are not running Python in an `openvino_env`  
environment. It is possible use the notebooks in a different  
environment, but if you run into trouble, please follow the instructions  
in the README to install and activate the `openvino_env` environment. 

The Python version in openvino_env does not match the openvino_env Jupyter kernel. 
This may not be an issue. If you experience issues, please follow the instructions 
in the README to reinstall the kernel.

`pip check` shows broken requirements:
CompletedProcess(args=['pip', 'check'], returncode=1, stdout='paddleclas 2.5.1 requires easydict, which is not installed.\ngoogle-auth 2.22.0 has requirement urllib3<2.0,
 but you have urllib3 2.0.4.\nnncf 2.5.0 has requirement numpy<1.24,>=1.19.1, but you have numpy 1.25.2.\nnncf 2.5.0 has requirement pandas<2.1,>=1.1.5, but you have pand
as 2.1.0.\nnncf 2.5.0 has requirement pyparsing<3.0, but you have pyparsing 3.0.9.\nopenvino-dev 2023.0.0 has requirement openvino==2023.0.0, but you have openvino 2023.1
.0.dev20230811.\npaddleclas 2.5.1 has requirement faiss-cpu==1.7.1.post2, but you have faiss-cpu 1.7.4.\npaddleclas 2.5.1 has requirement gast==0.3.3, but you have gast 0
.4.0.\ntensorflow 2.12.0 has requirement numpy<1.24,>=1.22, but you have numpy 1.25.2.\n')

The README.md file is located in the openvino_notebooks directory  
and at https://github.com/openvinotoolkit/openvino_notebooks 
Broken requirements are often harmless, but could cause issues.
```

**Additional context**

Might be an environment issue?

**Comment by Iffa-Meah** [comment] 2023-09-14 00:50
@dnoliver I'm seeing the same issue as yours even from a freshly created env.
<img width="845" alt="1302_2" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/0de952c0-9054-4d78-8672-64cff04017e4">


[error.txt](https://github.com/openvinotoolkit/openvino_notebooks/files/12602798/error.txt)

We'll further investigate this.

**Comment by avitial** [comment] 2023-09-15 20:03
@dnoliver the issue is caused by AUTO plugin not supporting INFERENCE_PRECISION_HINT property. We have submitted this as a bug, we will share more details as they become available. 

Ref. 120638

**Comment by eaidova** [comment] 2023-09-20 06:48
fix for optimum-intel: https://github.com/huggingface/optimum-intel/pull/433

**Comment by avitial** [comment] 2023-10-02 02:55
Closing this as PR has been merged to master branch. Feel free to reopen to ask additional questions related to this topic.

**Closed by avitial** 2023-10-02 02:55 UTC
Labels: bug, PSE, category: AUTO
