### ISSUE TITLE
mLLAMA 3.2 Output Issue and Gradio Error on Intel SPR Machine

### ISSUE THREAD

**Issue by saranyabalakumar** [openvinotoolkit/openvino_notebooks#2442] opened 2024-10-10 10:29 UTC
I'm running mLLAMA 3.2 on two machines:

Intel 4th Gen SPR server
NVIDIA GPU machine
On the NVIDIA GPU machine, everything works fine. But on the Intel SPR machine, the output is strange (!!!!!!!!!!!!!!!!!!), and Gradio gives errors when I try to open it on both the server and cloud setups.

It seems like the issue is specific to the Intel SPR machine. Any ideas on what might be causing this?

![Screenshot](https://github.com/user-attachments/assets/c5dc8b2f-4d68-4476-b833-deb0779ccce8)

**Comment by brmarkus** [comment] 2024-10-10 11:02
Can you provide more details, please?
On the server machine, are you using Jupyter-notebook directly (the server with a monitor connected), or remotely (e.g. screen-forwarding?

Which OS, which OS-version, which Python version, which version of OpenVINO-Notebooks?

You asked the question "To provide all the information in csv format from the images?".
Which output issue do you mean, seeing all those "!!!"?

Do you see the same issues&errors when using another picture, another question?

**Comment by saranyabalakumar** [comment] 2024-10-10 12:56
I am using the server machine remotely. I convert the Jupyter notebook code to Python scripts and use them for inference.

OS: Ubuntu Linux  
Kernel Version: 6.5.0-41-generic
Ubuntu version : 22.04.2
Python version: 3.10.15
OpenVINO-Notebooks Version: latest

I tried using one or more images with prompts, but the output response took a long time and all I got was '!!!'.
![Screenshot from 2024-10-03 12-48-35](https://github.com/user-attachments/assets/17c7df01-aa40-4c17-8ea3-19d4940993e0)

**Comment by brmarkus** [comment] 2024-10-10 13:07
For consistency check, would you be able to install the prerequisites and the packages mentioned in this notebook on another (non-SPR-)machine - and run your ported Python script?
It could be related to the CPU-instruction-sets mentioend in the log-messages, could also be due to prerequisites, or due to the ported Python script...

Maybe the dev-team anyway will ask you to share the ported Python-script for reproduction and deeper analysis as well as the output of `pip freeze`.

**Comment by saranyabalakumar** [comment] 2024-10-10 13:16
Sure, I can install the prerequisites and packages mentioned in the notebook on a non-SPR machine 
[freeze.txt](https://github.com/user-attachments/files/17328674/freeze.txt)

**Comment by rayzinnz** [comment] 2024-11-23 18:30
> I am using the server machine remotely. I convert the Jupyter notebook code to Python scripts and use them for inference.
> 
> OS: Ubuntu Linux Kernel Version: 6.5.0-41-generic Ubuntu version : 22.04.2 Python version: 3.10.15 OpenVINO-Notebooks Version: latest
> 
> I tried using one or more images with prompts, but the output response took a long time and all I got was '!!!'. ![Screenshot from 2024-10-03 12-48-35](https://private-user-images.githubusercontent.com/144224073/375382098-17c7df01-aa40-4c17-8ea3-19d4940993e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODYzNjQsIm5iZiI6MTczMjM4NjA2NCwicGF0aCI6Ii8xNDQyMjQwNzMvMzc1MzgyMDk4LTE3YzdkZjAxLWFhNDAtNGMxNy04ZWEzLTE5ZDQ5NDA5OTNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxODIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjk5NjlhOTM1Y2JkMWRjODNkN2E3NDU5MGYxNjVhNjU5ZDhhZDk3NWJlOWQwZjFjNmQxMTMyNDU0ZGNlYWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.atqOizlRp1YkiAOtwyH-pkgBmEOh6jMrcwsRk-A7bKM)

I get this exact same issue, and only with the mllama-3.2 notebook. Other LLM-only openvino notebooks (no vision) work fine. I also ran the mllama-3.2 openvino model without any compression, and same issue. Running Llama-3.2-11B-Vision-Instruct without conversion to openvino and using MllamaForConditionalGeneration directly works fine.

**Comment by avitial** [comment] 2024-12-26 20:05
Closing this as it can't be reproduced due to insufficient info (code snippet, app script for reproduction). Feel free to reopen to provide additional information and and ask additional questions related to this topic if issue persists.

**Closed as completed by avitial** 2024-12-26 20:05 UTC
Labels: support_request, category: CPU
