### ISSUE TITLE
kernel crashing while running 227

### ISSUE THREAD

**Issue by Snuupy** [openvinotoolkit/openvino_notebooks#1078] opened 2023-05-25 09:19 UTC
**Describe the bug**

Kernel gets killed on cell 17 of notebook in trying to process the audio.

 **Expected behavior**

Kernel should not be killed.

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
- [x] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

Note: I used the docker install.

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.

Unable to run `python check_install.py` because it's running in a docker container. Is there a different command to use for docker installs to check the install? As far as I understand the container includes the necessary dependencies and so it should not have dependency issues. The docker command used is as follows:

```
docker run -it \
	--name "openvino_notebooks" \
	--device=/dev/dri --group-add=$(stat -c "%g" /dev/dri/render* | head -n 1) \
	-p 8888:8888 \
	-v "/mnt/media/videos/:/media" \
	openvino_notebooks
```

running Ubuntu 23.04 on an Intel N5095.

**Additional context**

I replaced `output_file = Path("downloaded_video.mp4")` with my own mp4 file on the mount point.

My minipc is running with 8GB RAM, so I increased swap file to 16GB. The kernel still crashed so it doesn't look like a RAM issue. What needs to be done to fix this?

Edit: actually the youtube downloader doesn't work either but I'm sure people know how to use yt-dlp :)

**Comment by avitial** [comment] 2023-06-23 20:18
@Snuupy does the notebook execute normally while running with default output video file and without modifications? Before trying your own input video and changes, make sure the notebook executes normally without modifications. 

Once confirmed working make sure the video sample file that you are using isn't corrupted, and that file can be found and used normally within the notebook. 

Note I am not able to reproduce the problem you reported while using Ubuntu 22.04, so if you have any other details to reproduce the issue please share them.

**Comment by avitial** [comment] 2023-07-06 21:14
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Closed by avitial** 2023-07-06 21:14 UTC
Labels: support_request
