### ISSUE TITLE
Installed openvino notebook using docker. But check_install.py failed

### ISSUE THREAD

**Issue by gooishin** [openvinotoolkit/openvino_notebooks#2013] opened 2024-05-10 09:40 UTC
**Describe the bug**
I get this message after install using docker. 
Docker install command:  docker build -t openvino_notebooks .

> Successfully built f30e6fa7e919 
>Successfully tagged openvino_notebooks:latest

Docker run command:
docker run -it -v /etc/group:/etc/group  --device=/dev/dri --group-add=$(stat -c "%g" /dev/dri/render* | head -n 1) --group-add=$(stat -c "%g" /dev/dri/card* | head -n 1) -p 8888:8888 openvino_notebooks

But when i run check_install.py, it shows some error

```
(app-root) bash-4.4$ python check_install.py 
System information:
Python executable: /opt/app-root/bin/python
Pip version: 23.3.2
OpenVINO source: /opt/app-root/lib64/python3.8/site-packages/openvino
OpenVINO IE version: 2024.1.0-15008-f4afc983258-releases/2024/1
OpenVINO environment activated: NOT OK
Jupyter kernel installed for openvino_env: NOT OK
Python version: 3.8 OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK

It appears that you are not running Python in an `openvino_env` 
environment. It is possible use the notebooks in a different 
environment, but if you run into trouble, please follow the instructions 
in the README to install and activate the `openvino_env` environment.

The Python version in openvino_env does not match the openvino_env Jupyter kernel.
This may not be an issue. If you experience issues, please follow the instructions
in the README to reinstall the kernel.

The README.md file is located in the openvino_notebooks directory 
and at https://github.com/openvinotoolkit/openvino_notebooks
```
i'm using docker, how do I create and source the environment?

 **Expected behavior**
check_install.py pass

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[ x ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks/wiki/Docker

** Environment information **
As stated above
 
**Additional context**
Just a feedback, when run docker container, there is no check_install.py script, i copy it manually into jupyter notebook via web browser.

**Comment by gooishin** [comment] 2024-05-13 01:01
I was trying to run notebook hello-npu, but it only shows CPU. Hence im using check_install.py . If i install openvino natively, query device able to get CPU, GPU and NPU.

**Comment by gooishin** [comment] 2024-05-14 01:32
> You might need to add `--device=/dev/accel` to the docker run command line - which I saw here: "https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#step-5-run-intel-dl-streamer-pipeline-framework-container"

I tried with `--device=/dev/accel` , still only able to detect CPU

**Comment by Iffa-Intel** [comment] 2024-05-16 07:14
@gooishin Try upgrading your Docker version to the latest version using the command:
sudo apt-get update
sudo apt-get upgrade docker-ce

I assume you already set the Docker to be run as non-root user. 
However, try to run the command with sudo: "sudo docker build -t openvino_notebooks" 
as in this case [#2012](https://github.com/openvinotoolkit/openvino_notebooks/issues/2012) these solved building issues.

**Comment by gooishin** [comment] 2024-05-17 01:03
@Iffa-Intel , i have updated the docker-ce and reinstall using sudo. But still im only able to see CPU.
command:

docker run -it --name test_notebooks -v /etc/group:/etc/group  --device=/dev/dri --device=/dev/accel --group-add=$(stat -c "%g" /dev/dri/render* | head -n 1) -p 8888:8888 openvino_notebooks

This is notebook hello-npu. Expecting to see CPU, GPU and NPU here.
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/100290970/583c2266-8208-48b2-8e49-4fd64b6868f6)

**Comment by avitial** [comment] 2024-05-23 15:28
@gooishin can you share the CPU SKU/Model you are using? Post the output of `lscpu`.

**Comment by avitial** [comment] 2024-06-13 00:11
@gooishin so part of the issue is that the NPU driver needs to be installed on the container itself to be able to utilize the plugin with the OpenVINO Notebooks. So with that in mind you can try to modify the provided [Dockerfile](https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/Dockerfile) and add the NPU driver build and install steps (build instructions [here](https://github.com/intel/linux-npu-driver)) or you can use one of the pre-built Docker images (i.e. docker pull openvino/ubuntu22_dev:latest), install the NPU driver (build steps [here](https://github.com/intel/linux-npu-driver)) within the container and install the OpenVINO Notebooks. I've tried the second option and while running [hello_query_device.py](https://raw.githubusercontent.com/openvinotoolkit/openvino/master/samples/python/hello_query_device/hello_query_device.py)) the NPU device is detected (identified as '_AI Boost_'). 

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/20826577/b9083928-0935-4fcc-8f90-4e78b3c47e60)

**Comment by avitial** [comment] 2024-06-18 18:39
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.

**Closed by avitial** 2024-06-18 18:39 UTC
Labels: PSE, support_request, category: NPU
